-- Crear la tabla si no existe
CREATE TABLE IF NOT EXISTS public."Ejercicios" (
    nombre TEXT PRIMARY KEY,
    categoria TEXT,
    peso_corporal BOOLEAN,
    sinonimos TEXT[],
    factor_carga FLOAT8,
    mapeo_anatomico JSONB
);

-- Limpiar tabla antes de insertar para evitar duplicados
TRUNCATE TABLE public."Ejercicios";

INSERT INTO public."Ejercicios" (nombre, categoria, peso_corporal, sinonimos, factor_carga, mapeo_anatomico)
VALUES 
('Press banca', 'Pecho', false, ARRAY['press banca', 'pecho plano', 'bench press'], 1.0, '{"chest": 1.0, "triceps": 0.6, "front-deltoids": 0.4}'),
('Press plano con mancuernas', 'Pecho', false, ARRAY['press mancuernas pecho', 'dumbbell bench press'], 1.0, '{"chest": 1.0, "triceps": 0.5, "front-deltoids": 0.4}'),
('Press superior con mancuernas', 'Pecho', false, ARRAY['press inclinado mancuernas', 'incline dumbbell press'], 1.0, '{"chest": 1.0, "front-deltoids": 0.7, "triceps": 0.5}'),
('Floor Press', 'Pecho', false, ARRAY['floor press'], 1.0, '{"chest": 1.0, "triceps": 0.5, "front-deltoids": 0.3}'),
('Flexiones', 'Pecho', true, ARRAY['flexiones', 'push ups', 'flexion'], 0.7, '{"chest": 1.0, "triceps": 0.5, "front-deltoids": 0.4, "abs": 0.2}'),
('Flexiones declinadas', 'Pecho', true, ARRAY['flexiones declinadas'], 0.75, '{"chest": 1.0, "front-deltoids": 0.6, "triceps": 0.5}'),
('Flexiones inclinadas', 'Pecho', true, ARRAY['flexiones inclinadas'], 0.6, '{"chest": 1.0, "triceps": 0.4}'),
('Flexiones rusas', 'Pecho', true, ARRAY['flexiones rusas', 'russian push ups'], 0.9, '{"chest": 0.8, "triceps": 0.9, "abs": 0.6, "forearm": 0.5}'),
('Flexiones diamante', 'Pecho', true, ARRAY['flexiones diamante', 'diamond push ups'], 0.8, '{"triceps": 1.0, "chest": 0.7, "front-deltoids": 0.4}'),
('Flexiones explosivas', 'Pecho', true, ARRAY['flexiones con palmada', 'flexiones explosivas'], 1.1, '{"chest": 1.0, "triceps": 0.7, "front-deltoids": 0.5}'),
('Press inclinado', 'Pecho', false, ARRAY['press inclinado', 'press de banca inclinado', 'incline bench press'], 1.0, '{"chest": 1.0, "front-deltoids": 0.7, "triceps": 0.5}'),
('Press declinado', 'Pecho', false, ARRAY['press declinado', 'press de banca declinado', 'decline bench press'], 1.0, '{"chest": 1.0, "triceps": 0.4}'),
('Press de pecho en máquina', 'Pecho', false, ARRAY['chest press machine', 'press maquina'], 0.9, '{"chest": 1.0, "triceps": 0.4, "front-deltoids": 0.3}'),
('Press inclinado en máquina convergente', 'Pecho', false, ARRAY['press convergente', 'incline machine press'], 0.95, '{"chest": 1.0, "front-deltoids": 0.6, "triceps": 0.4}'),
('Crossover en poleas', 'Pecho', false, ARRAY['cruces de poleas', 'cable crossover'], 0.6, '{"chest": 1.0, "front-deltoids": 0.2}'),
('Contractora de pecho', 'Pecho', false, ARRAY['pec deck', 'peck deck', 'contractora', 'aperturas en maquina'], 0.55, '{"chest": 1.0}'),
('Fondos en paralelas', 'Pecho', true, ARRAY['fondos pecho', 'chest dips', 'fondos en paralelas enfoque esternal'], 0.95, '{"chest": 1.0, "triceps": 0.7, "front-deltoids": 0.5}'),
('Sentadilla', 'Pierna', false, ARRAY['sentadilla', 'sentadillas', 'air squats'], 1.0, '{"quadriceps": 1.0, "gluteal": 0.8, "hamstring": 0.4, "lower-back": 0.3, "abs": 0.2}'),
('Sentadilla Sumo', 'Pierna', false, ARRAY['sentadilla sumo', 'sentadillas sumo'], 1.05, '{"quadriceps": 0.8, "adductor": 1.0, "gluteal": 0.9, "hamstring": 0.5}'),
('Sentadilla Búlgara', 'Pierna', false, ARRAY['sentadilla bulgara', 'bulgarian split squat'], 0.9, '{"quadriceps": 1.0, "gluteal": 1.0, "hamstring": 0.4, "adductor": 0.3}'),
('Peso muerto', 'Pierna', false, ARRAY['peso muerto', 'deadlift'], 1.2, '{"lower-back": 1.0, "hamstring": 0.9, "gluteal": 0.8, "trapezius": 0.6, "forearm": 0.5}'),
('Peso Muerto Sumo', 'Pierna', false, ARRAY['peso muerto sumo'], 1.2, '{"adductor": 1.0, "gluteal": 0.9, "hamstring": 0.7, "lower-back": 0.8}'),
('Puente Gluteos', 'Pierna', false, ARRAY['puente gluteos', 'extension de cadera'], 0.8, '{"gluteal": 1.0, "hamstring": 0.6, "lower-back": 0.3}'),
('Prensa de piernas 45°', 'Pierna', false, ARRAY['prensa', 'leg press', 'prensa 45'], 1.1, '{"quadriceps": 1.0, "gluteal": 0.6, "hamstring": 0.3}'),
('Extensión de cadera en polea', 'Pierna', false, ARRAY['patada de gluteo', 'glute kickback'], 0.5, '{"gluteal": 1.0, "hamstring": 0.3}'),
('Empuje de cadera', 'Pierna', false, ARRAY['hip thrust', 'empuje cadera'], 1.1, '{"gluteal": 1.0, "hamstring": 0.5, "lower-back": 0.2}'),
('Extensión de rodilla en máquina', 'Pierna', false, ARRAY['extension de pierna', 'leg extension'], 0.6, '{"quadriceps": 1.0}'),
('Sentadilla en máquina', 'Pierna', false, ARRAY['hack squat', 'sentadilla hack', 'sentadilla multipower'], 1.0, '{"quadriceps": 1.0, "gluteal": 0.7, "hamstring": 0.3}'),
('Aducción de cadera en máquina', 'Pierna', false, ARRAY['aductor maquina', 'adductor machine'], 0.5, '{"adductor": 1.0}'),
('Flexión plantar de pie', 'Pierna', false, ARRAY['gemelos de pie', 'calf raise'], 0.5, '{"calves": 1.0}'),
('Flexión plantar sentado', 'Pierna', false, ARRAY['soleo', 'gemelo sentado'], 0.45, '{"calves": 1.0}'),
('Jalón lateral', 'Espalda', false, ARRAY['jalon al pecho', 'lat pulldown'], 1.0, '{"upper-back": 1.0, "biceps": 0.5, "back-deltoids": 0.4, "forearm": 0.3}'),
('Dominadas', 'Espalda', true, ARRAY['dominadas', 'pull ups'], 1.0, '{"upper-back": 1.0, "biceps": 0.6, "forearm": 0.5, "abs": 0.3}'),
('Dominadas supinas', 'Espalda', true, ARRAY['dominadas supinas', 'chin ups'], 1.0, '{"biceps": 1.0, "upper-back": 0.8, "forearm": 0.5}'),
('Dominadas australianas', 'Espalda', true, ARRAY['dominadas australianas'], 0.8, '{"upper-back": 1.0, "back-deltoids": 0.6, "biceps": 0.5, "forearm": 0.4}'),
('Facepull', 'Espalda', false, ARRAY['face pull'], 0.5, '{"back-deltoids": 1.0, "trapezius": 0.7, "upper-back": 0.5}'),
('Remo horizontal en polea baja', 'Espalda', false, ARRAY['remo sentado', 'seated row', 'remo polea'], 0.9, '{"upper-back": 1.0, "biceps": 0.4, "forearm": 0.3}'),
('Remo unilateral con mancuerna', 'Espalda', false, ARRAY['remo mancuerna', 'one arm row'], 0.9, '{"upper-back": 1.0, "biceps": 0.4, "forearm": 0.4}'),
('Pájaros en máquina', 'Espalda', false, ARRAY['reverse fly', 'deltoide posterior maquina'], 0.45, '{"back-deltoids": 1.0, "upper-back": 0.4}'),
('Pull over en polea alta', 'Espalda', false, ARRAY['pull over brazos extendidos', 'straight arm pulldown'], 0.6, '{"upper-back": 1.0, "triceps": 0.3, "chest": 0.2}'),
('Remo inclinado con barra', 'Espalda', false, ARRAY['barbell row', 'remo barra'], 1.1, '{"upper-back": 1.0, "lower-back": 0.6, "biceps": 0.5, "forearm": 0.4}'),
('Aducción escapular en máquina', 'Espalda', false, ARRAY['escapulas maquina', 'scapular adduction'], 0.4, '{"trapezius": 1.0, "upper-back": 0.8}'),
('Remo con agarre ancho en polea', 'Espalda', false, ARRAY['wide grip row'], 0.9, '{"upper-back": 1.0, "back-deltoids": 0.5}'),
('Remo unilateral en polea baja', 'Espalda', false, ARRAY['single arm cable row', 'remo unilateral polea'], 0.85, '{"upper-back": 1.0, "biceps": 0.4}'),
('Press militar', 'Hombro', false, ARRAY['press militar', 'shoulder press'], 0.85, '{"front-deltoids": 1.0, "triceps": 0.6, "upper-back": 0.4, "abs": 0.3}'),
('Snatch con mancuerna', 'Hombro', false, ARRAY['snatch con mancuerna'], 1.2, '{"front-deltoids": 0.8, "trapezius": 0.7, "quadriceps": 0.5, "gluteal": 0.5, "lower-back": 0.6}'),
('Jerk', 'Hombro', false, ARRAY['jerk'], 1.1, '{"front-deltoids": 1.0, "triceps": 0.7, "quadriceps": 0.4}'),
('Handstand Push-Up', 'Hombro', true, ARRAY['flexiones a pino', 'hspu', 'handstand push up'], 1.2, '{"front-deltoids": 1.0, "triceps": 0.8, "trapezius": 0.6, "upper-back": 0.4}'),
('Pike Push-Up', 'Hombro', true, ARRAY['pike push up', 'flexiones en v'], 0.9, '{"front-deltoids": 1.0, "triceps": 0.6, "upper-back": 0.5}'),
('Elevaciones laterales en máquina', 'Hombro', false, ARRAY['lateral raise machine', 'hombro lateral maquina'], 0.45, '{"side-deltoids": 1.0, "front-deltoids": 0.3}'),
('Curl bíceps', 'Brazos', false, ARRAY['curl biceps', 'curl bíceps supino'], 0.5, '{"biceps": 1.0, "forearm": 0.4}'),
('Curl sentado', 'Brazos', false, ARRAY['curl de biceps sentado', 'seated curl'], 0.5, '{"biceps": 1.0}'),
('Curl barra EZ', 'Brazos', false, ARRAY['curl con barra EZ', 'ez bar curl'], 0.55, '{"biceps": 1.0, "forearm": 0.3}'),
('Curl martillo', 'Brazos', false, ARRAY['martillo', 'curl neutro'], 0.5, '{"forearm": 1.0, "biceps": 0.6}'),
('Curl de bíceps en polea doble', 'Brazos', false, ARRAY['biceps polea', 'cable bicep curl'], 0.5, '{"biceps": 1.0, "forearm": 0.2}'),
('Curl Bayesiano', 'Brazos', false, ARRAY['bayesian curl', 'curl en elongacion'], 0.45, '{"biceps": 1.0}'),
('Curl Spider', 'Brazos', false, ARRAY['spider curl', 'curl araña'], 0.45, '{"biceps": 1.0}'),
('Extensión de tríceps en polea alta', 'Brazos', false, ARRAY['triceps polea cuerda', 'cable triceps extension'], 0.45, '{"triceps": 1.0}'),
('Press de tríceps en máquina', 'Brazos', false, ARRAY['triceps machine press', 'maquina triceps'], 0.7, '{"triceps": 1.0, "chest": 0.2}'),
('Press Francés', 'Brazos', false, ARRAY['press frances barra ez', 'skull crusher'], 0.6, '{"triceps": 1.0}'),
('Extensión de tríceps tras nuca', 'Brazos', false, ARRAY['copa triceps', 'overhead triceps extension'], 0.5, '{"triceps": 1.0}'),
('Fondos tríceps', 'Brazos', true, ARRAY['fondos', 'dips'], 0.9, '{"triceps": 1.0, "chest": 0.4, "front-deltoids": 0.4}'),
('Patada de tríceps', 'Brazos', false, ARRAY['patada triceps', 'triceps kickback'], 0.4, '{"triceps": 1.0}'),
('Thruster', 'Full Body', false, ARRAY['thruster'], 1.3, '{"quadriceps": 0.9, "gluteal": 0.7, "front-deltoids": 0.8, "triceps": 0.6, "abs": 0.4}'),
('Clean and jerk', 'Full Body', false, ARRAY['clean and jerk'], 1.5, '{"quadriceps": 0.8, "gluteal": 0.7, "hamstring": 0.7, "trapezius": 0.8, "front-deltoids": 0.8, "triceps": 0.6, "lower-back": 0.7}'),
('Clean', 'Full Body', false, ARRAY['clean'], 1.3, '{"quadriceps": 0.9, "gluteal": 0.8, "hamstring": 0.8, "trapezius": 0.7, "lower-back": 0.7, "forearm": 0.5}'),
('Devil press', 'Full Body', false, ARRAY['devil press'], 1.4, '{"chest": 0.6, "front-deltoids": 0.8, "quadriceps": 0.7, "gluteal": 0.6, "hamstring": 0.6, "triceps": 0.5, "abs": 0.5}');